### PR TITLE
Explicitly stop the timer when the connection is closed.

### LINKED ISSUE #137: Too high memory usage
Stress testing ck-server with NumConn=0 and making only around 70 Cloak sessions, it's already consuming 180 MB of RAM and it continues to climb. It doesn't seem to be releasing memory properly even after the connections are stopped. There seems to be a memory leak.

### PR DESCRIPTION
**Pull request by notsure2**
Fixes #137 again.

### CODE REVIEW

**Comment by cbeuw** [comment]
This won't work either, because the goroutine started on each inocation of broadcastAfter() will not actually return on timer.Stop() (it doesn't actually close the channel). I'm trying to see if there is a solution that involves a single long living broadcaster goroutine

**Comment by notsure2** [comment]
Then how do you cancel an in-flight timer ? I am under the impression that calling timer.Stop and then calling broadcast will wake the goroutine, which will call Stop again, which will return false, and then it will then drain the channel and terminate...

Or am I mistaken ? I'm not very familiar, so any correction will be appreciated.

**Comment by cbeuw** [comment]
>Then how do you cancel an in-flight timer 

I don't think golang's `time` module provides any convenient way of doing this, because timer.C only ever gets filled when the timer fires. There's no way of unblocking an listener other than making the timer fire. One way is to have another channel that gets unblocked inside Close(), and put this channel and the timer channel together in a `select` statement:
```go
for {
	select {
               	case <-p.timer.C:
               	p.rwCond.Broadcast()
		case <-p.closeCh:
		return
	}
}
```

Alternatively, we could probably do this
```go
for {
	<-p.timer.C
	if p.closed {
		return
	} else {
		p.rwCond.Broadcast()
	}
}
```
And in Close() we do `p.timer.Reset(0)` so the above listener will get unblocked immediately. It seems to work but I need to do more tests

**Comment by notsure2** [comment]
Even if you unblock the goroutine by selecting on another channel that gets filled during close, don't you still need to clean up the timer (there's a runtimeTime inside) and a channel also inside that need be cleaned up, otherwise it's still leaking...

**Comment by notsure2** [comment]
OK i implemented the second channel solution (in my updated push). But memory usage is still climbing... Just that the profile now changed. I will update the bug report. #137

**Comment by notsure2** [comment]
@cbeuw Please check the updated branch, the issue is much much better now, almost solved. I'll leave it running for long time to confirm it.

**Comment by notsure2** [comment]
Memory use is even better now, only 25 MB RAM usage stable with 110 active sessions!

**Comment by cbeuw** [comment]
That's great to hear. Thanks a lot for the help!

**Pull request merged**
